version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pharmacy_pos_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pharmacy_pos
      POSTGRES_USER: pharmacy_user
      POSTGRES_PASSWORD: pharmacy_password_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    # No port forwarding - internal access only via pgAdmin or API
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/backups:/backups
    networks:
      - pharmacy_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pharmacy_user -d pharmacy_pos"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pharmacy_pos_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pharmacypos.com
      PGADMIN_DEFAULT_PASSWORD: admin_password_2024
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "48080:80"  # New port: 48080
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - pharmacy_network
    depends_on:
      postgres:
        condition: service_healthy

  api:
    build: .
    container_name: pharmacy_pos_api
    restart: unless-stopped
    ports:
      - "41300:3000"  # New port: 41300 for Node.js API
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=pharmacy_pos
      - DB_USER=pharmacy_user
      - DB_PASSWORD=pharmacy_password_2024
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - pharmacy_network
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: pharmacy_pos_nginx
    restart: unless-stopped
    ports:
      - "40080:80"  # New port: 40080 for web HTML
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./assets/login.html:/usr/share/nginx/html/login.html:ro
      - ./assets/dashboard.html:/usr/share/nginx/html/dashboard.html:ro
      - ./assets:/usr/share/nginx/html/assets:ro
    networks:
      - pharmacy_network
    depends_on:
      - api

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  pharmacy_network:
    driver: bridge
